import avatar from "assets/img/faces/marc.jpg"

const members = [
    {
        lastname:"victor",
        firstname:"dele",
        photo:avatar,
        email:"victor@gmail.com",
        dob:"20-04-1900",
        lga:"kanam",
        gender:"male",
        phone:"08012341234",
        education:"BSc",
        maritalStatus:"single",
        diasbility:"no",
        homeAddress:"21T Rukuba Road, jos",
        course:"Android Engineering",
        institution:" Maxi University",
        yearOfGrad:"2000",
        role:"user",
        id:"1234567890"
    },
    {
        lastname:"ade",
        firstname:"bennie",
        photo:avatar,
        email:"bennie@gmail.com",
        dob:"20-04-1900",
        lga:"pankshin",
        gender:"male",
        phone:"08012341234",
        education:"BSc",
        maritalStatus:"single",
        diasbility:"no",
        homeAddress:"21T Rukuba Road, jos",
        course:"Android Engineering",
        institution:" Maxi University",
        yearOfGrad:"2000",
        role:"user",
        id:"1234567890"
    },
    {
        lastname:"simi",
        firstname:"dung",
        photo:avatar,
        email:"dung@gmail.com",
        dob:"20-04-1900",
        lga:"jos-south",
        gender:"female",
        phone:"08012341234",
        education:"BSc",
        maritalStatus:"single",
        diasbility:"no",
        homeAddress:"21T Rukuba Road, jos",
        course:"Android Engineering",
        institution:" Maxi University",
        yearOfGrad:"2000",
        role:"user",
        id:"1234567890"
    },
    {
        lastname:"bule",
        firstname:"fom bot",
        photo:avatar,
        email:"fom@gmail.com",
        dob:"20-04-1900",
        lga:"riyom",
        gender:"male",
        phone:"08012341234",
        education:"BSc",
        maritalStatus:"single",
        diasbility:"no",
        homeAddress:"21T Rukuba Road, jos",
        course:"Engineering",
        institution:" Maxi University",
        yearOfGrad:"2000",
        role:"user",
        id:"1234567890"
    },
    {
        lastname:"felix",
        firstname:"gotak",
        photo:avatar,
        email:"gotak@gmail.com",
        dob:"20-04-1900",
        lga:"barkin ladi",
        gender:"male",
        phone:"08012341234",
        education:"BSc",
        maritalStatus:"single",
        diasbility:"yes",
        homeAddress:"21T Rukuba Road, jos",
        course:"Accounting",
        institution:" Maxi University",
        yearOfGrad:"2000",
        role:"user",
        id:"1234567890"
    },
    {
        lastname:"bala",
        firstname:"Hele",
        photo:avatar,
        email:"hele@gmail.com",
        dob:"20-04-1900",
        lga:"bassa",
        gender:"male",
        phone:"08012341234",
        education:"BSc",
        maritalStatus:"single",
        diasbility:"no",
        homeAddress:"21T Rukuba Road, jos",
        course:"Pharmacy",
        institution:" Maxi University",
        yearOfGrad:"2000",
        role:"user",
        id:"1234567890"
    },
    {
        lastname:"Nanbam",
        firstname:"kumtur",
        photo:avatar,
        email:"nanbam@gmail.com",
        dob:"20-04-1900",
        lga:"langtang",
        gender:"female",
        phone:"08012341234",
        education:"BSc",
        maritalStatus:"single",
        diasbility:"yes",
        homeAddress:"21T Rukuba Road, jos",
        course:"",
        institution:" Maxi University",
        yearOfGrad:"2000",
        role:"user",
        id:"1234567890"
    },
    {
        lastname:"George",
        firstname:"asak",
        photo:avatar,
        email:"ujah@gmail.com",
        dob:"20-04-1900",
        lga:"bassa",
        gender:"male",
        phone:"08012341234",
        education:"BSc",
        maritalStatus:"single",
        diasbility:"no",
        homeAddress:"21T Rukuba Road, jos",
        course:"Android Engineering",
        institution:" Maxi University",
        yearOfGrad:"2000",
        role:"user",
        id:"1234567890"
    },
    {
        lastname:"ninmyel",
        firstname:"Godwin ",
        photo:avatar,
        email:"godwin@gmail.com",
        dob:"20-04-1900",
        lga:"langtang-south",
        gender:"male",
        phone:"08012341234",
        education:"BSc",
        maritalStatus:"single",
        diasbility:"yes",
        homeAddress:"21T Rukuba Road, jos",
        course:"Econimics",
        institution:" Maxi University",
        yearOfGrad:"2000",
        role:"user",
        id:"1234567890"
    }
]

export default members;